### ISSUE TITLE
Start using pyproject.toml

### ISSUE THREAD

**Issue by 0dminnimda** [0dminnimda/pynalyser#14]
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
https://browniebroke.com/blog/convert-requirements-to-pyproject/
https://setuptools.pypa.io/en/latest/build_meta.html

**Comment by 9gl** [comment]
Hey @0dminnimda ,
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by 0dminnimda** [comment]
Hi @9gl!
Sure, the issue is that python communuty choose to move from setuptools specific configuration to independent one.
For more info: it was first introduced in [PEP 518](https://peps.python.org/pep-0518/) and later expanded in [PEP 517](https://peps.python.org/pep-0517/), [PEP 621](https://peps.python.org/pep-0621/) and [PEP 660](https://peps.python.org/pep-0660/)

But the task is essentially take the setup.py and convert it into pyproject.toml (and maybe setup.cfg)
Two links I put into the discription of the ticket will help you with that.

If you have any other quentions or need help don't hesitate to ping me!

**Comment by 0dminnimda** [comment]
Also it doesn't have to be all in one pr, you may initially just convert as much easy filds, and then work on harders parts in other prs

**Comment by 9gl** [comment]
ok

**Comment by 0dminnimda** [comment]
Yep, [here](https://github.com/0dminnimda/pynalyser/blob/main/setup.py) it is
You want to create a new branch and add the pyproject.toml in the same root folder as setup.py is in

**Comment by 9gl** [comment]
Could you assign me this issue

**Comment by 0dminnimda** [comment]
Sure

**Comment by 0dminnimda** [comment]
@9gl what are your plans on this?

**Comment by 9gl** [comment]
I am working on it
